### ISSUE TITLE
Sort user list on "Add Card" page

### ISSUE THREAD

**Issue by mlamparter** [Bucknell-ECE/PortalBox-ManagementPortal#28] opened 2020-01-21 13:37 UTC
When a user chooses to create a new card of type User, the User drop down list should be sorted in some fashion.  Perhaps alphabetically by first name?  Sorting alphabetically by last name would make more sense but would potentially be more difficult as the names are currently listed in format of (FirstName LastName).

Long term - could we consider changing the drop down menu to a searchable combo box?

**Comment by bu-tegan** [comment] 2020-01-24 15:03
Partial resolution in commit ed5ed66c78665d63005904dff37463629edb6861

**Comment by bu-tegan** [comment] 2020-02-05 20:09
What remains is a duplicate of Issue #9

**Closed by bu-tegan** 2020-02-05 20:09 UTC
Labels: enhancement
